version: '3.8'

services:
  postgres-service:
    hostname: postgres
    image: postgres
    container_name: postgres-crm-container
    restart: always
    networks:
      - my_network
    ports:
      - '5437:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: { }

networks:
  my_network: { }